homepepage/urls.py
from django.urls import path
from . import views

app_name = 'homepepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
]

story_8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepepage.urls')),
]

homepepage/models.py
from django.db import models

# Create your models here.

homepepage/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import requests


# Create your views here.
def index(request):
    return render(request, 'index.html')

def search(request):
    q = request.GET['q']
    
    # json_read = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + q)
    url_tujuan = 'https://www.googleapis.com/books/v1/volumes?q=' + q
    req = requests.get(url_tujuan)

    x = json.loads(req.content)

    return JsonResponse(x, safe=False)

homepepage/templates/index.html
 <!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script>
        const data_books_url = "{% url 'homepepage:search' %}?q=";
    </script>

    <title>Daijoubu?</title>
</head>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Dosis:wght@600&display=swap');
    body {
        background-color: #ffde22;
        font-family: 'Dosis', sans-serif;
        
    }
    #card {
        box-shadow: 0 0 5px rgba(225,225,225,1);
        padding-left: 50px;
        padding-top: 50px;
        padding-bottom: 50px;
        border-bottom-left-radius: 10px;
        border-bottom-right-radius: 10px;
    }
    .card {
        box-shadow: 0 6px 10px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
    }
    .card:hover {
        box-shadow: 0 10px 18px 0 rgba(0,0,0,0.2);
    }
    #kotak-atas {
        background-color: black;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
    }
    
</style>
<body>
    
    
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <div id="kotak-atas"  style="color: white;padding-top: 5px;">
                    <h2 style="margin-top: 30px; margin-bottom: 30px; margin-left: 30px;">Story 8 kroX</h2>
                    <h4 style="margin-bottom: 15px;margin-left: 30px;">Try to search BOOKS!</h4>
                    <div class="row">
                        <div class="col-8">
                            <input type="text" id="input" class="form-control" placeholder="Search The Books " style="margin-bottom: 50px;margin-left: 30px;">
                        </div>
                    </div>
                </div>
                
                <div id="card" style="background-color: white;"></div>
                
            </div>
        </div>
    </div>





    <script src=" {% static 'func.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>